runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/home.html
  upload: static/home\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: .*
  script: main.app

inbound_services:
- warmup

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
